name: Show Env variables


on:
  workflow_dispatch: 
    inputs: 
      environments:
        description: Select the environment you want
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stg
          - prd
           
      
      
env:
  NAME: Nitisha
  
jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - name: show plain text env
        run: echo "My name is ${{env.NAME}}"

