name: Show Env variables


on:
  workflow_dispatch: 
env:
  NAME: Nitisha
jobs:
  show-env:
    runs-on: ubuntu-latest
    steps:
      - name: show plain text env
        run: echo "My name is ${{env.NAME}}

